config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'posts#open_posts'

  get 'about', to: 'home#about'

  resources :posts do
    collection do
      get 'post_model_box'
      get 'open_posts'
    end
  end

  namespace :users do
    get 'login_model_box', to: 'users#login_model_box', as: :login_model_box
    get 'sign_up_model_box', to: 'users#sign_up_model_box', as: :sign_up_model_box
    get 'forgot_password_modal_box', to: 'users#forgot_password_modal_box', as: :forgot_password_modal_box
    get 'get_more_options', to: 'users#get_more_options', as: :get_more_options
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
module Users
    class UsersController < ApplicationController
        before_action :authenticate_user!, except: [:login_model_box, :sign_up_model_box, :forgot_password_modal_box]

        def login_model_box
            respond_to do |format|
                format.js { render 'users/login_model_box' }
            end
        end

        def sign_up_model_box
            respond_to do |format|
                format.js { render 'users/sign_up_model_box' }
            end
        end

        def forgot_password_modal_box
            respond_to do |format|
                format.js { render 'users/forgot_password_modal_box' }
            end
        end

        def get_more_options
            respond_to do |format|
                format.js   { render 'users/get_more_options' } # For JS requests
            end
        end
    end
end

app/views/users/partials/_forgot_password.html.erb
<%
    resource = User.new
    resource_name = :user
    devise_mapping = Devise.mappings[:user]
%>
<%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post, class: 'new_user d-flex justify-content-center flex-column align-items-center' }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>
 <div class="kae-form-group">
    <div class="field form-group">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="actions form-group text-center">
        <%= f.submit "Send me reset password", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>


<div class="d-flex justify-content-center">
    <%= link_to 'Sign up', users_sign_up_model_box_path, remote: true, id: 'showModalBtn', class: 'btn btn-link' %>
    <%= link_to 'Log in', users_login_model_box_path, remote: true, id: 'showModalBtn', class: 'btn btn-link' %>
</div>

app/views/users/partials/_more_options.html.erb
<div class="more_optionns">
    <div class="more_options_options">
        <b class="more_options_title">Posts</b>
        <div class="more_options_items">
        <%= link_to posts_path, class: 'more_option_item' do %>
            <i class="fa-solid fa-blog"></i>
        <% end %>
        </div>
    </div>
    <div class="more_options_options">
        <b class="more_options_title">Comments</b>
        <div class="more_options_items">
            <i class="fa-regular fa-comment"></i>
        </div>
    </div>
    <div class="more_options_options">
        <b class="more_options_title">Subscribers</b>
        <div class="more_options_items">
            <i class="fa-solid fa-envelopes-bulk"></i>
        </div>
    </div>
    <div class="more_options_options">
        <b class="more_options_title">Users</b>
        <div class="more_options_items">
            <i class="fa-solid fa-users"></i>
        </div>
    </div>
</div>

<style>
    .more_optionns{
        display: flex;
        flex-wrap: wrap;
    }
    .more_options_options{
        background-color: #FAF9F6;
        box-shadow: 0 3px 20px rgba(0, 0, 0, 0.2);
        margin: 5px;
        display: flex;
        flex-direction: column;
        padding: 15px;
    }
    .more_option_item{
        font-size: 25px;
        margin: 10px;
        color: #131516;
        cursor: pointer;
    }

    .more_option_item i:hover{
        color: #be7c68;
    }

    .more_options_title{
        color: #be7c68;
        cursor: pointer;
        font-size: 14px;
    }

</style>

app/views/users/partials/_sign_in.html.erb
<%
    resource = User.new
    resource_name = :user
%>

<%= form_for(resource, as: resource_name, url: session_path(resource_name),  html: { class: 'new_user d-flex justify-content-center flex-column align-items-center' }) do |f| %>
    <div class="kae-form-group">
        <div class="field form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>

        <div class="field form-group">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "current-password" %>
        </div>

        <div class="field form-group">
            <%= f.check_box :remember_me %>
            <%= f.label :remember_me %>
        </div>

        <div class="actions form-group text-center">
            <%= f.submit "Log in", class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

<div class="d-flex justify-content-center">
    <%= link_to 'Sign up', users_sign_up_model_box_path, remote: true, id: 'showModalBtn', class: 'btn btn-link' %>
     <%= link_to 'Forgot your password?', users_forgot_password_modal_box_path, remote: true, id: 'showModalBtn', class: 'btn btn-link' %>
</div>

app/views/users/partials/_sign_up.html.erb
<%
  resource = User.new
  resource_name = :user
%>
<%= form_for(resource, as: resource_name, url: user_registration_path, html: { class: 'new_user d-flex justify-content-center flex-column align-items-center' }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>
  <div class="kae-form-group">
    <div class="field form-group">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field form-group">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field form-group">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="actions form-group text-center">
      <%= f.submit "Sign up", class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

<div class="d-flex justify-content-center">
  <%= link_to 'Log in', users_login_model_box_path, remote: true, id: 'showModalBtn', class: 'btn btn-link' %>
</div>