config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'posts#open_posts'

  get 'about', to: 'home#about'

  resources :posts do
    collection do
      get 'post_model_box'
      get 'open_posts'
    end
  end

  namespace :users do
    get 'login_model_box', to: 'users#login_model_box', as: :login_model_box
    get 'sign_up_model_box', to: 'users#sign_up_model_box', as: :sign_up_model_box
    get 'forgot_password_modal_box', to: 'users#forgot_password_modal_box', as: :forgot_password_modal_box
    get 'get_more_options', to: 'users#get_more_options', as: :get_more_options
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    # has_many :comments, dependent: :destroy
    # has_many :likes, as: :likeable, dependent: :destroy
    # has_many :post_tags, dependent: :destroy
    # has_many :tags, through: :post_tags
    # has_many :post_categories, dependent: :destroy
    # has_many :categories, through: :post_categories
    has_many :attachments, as: :attachmentable, dependent: :destroy
    accepts_nested_attributes_for :attachments, allow_destroy: true
  
    validates :title, presence: true
    validates :body, presence: true
    validates :position, presence: true, numericality: { only_integer: true }, uniqueness: true

    enum status: { draft: 1, published: 2, archived: 3 }

  def image_url
        image = self.attachments.last
        if image.present? && image.file.attached?
          Rails.application.routes.url_helpers.rails_representation_url(image.file, only_path: true)
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: %i[show edit update destroy]
    before_action :authenticate_user!, except: [:open_posts, :show]
  
    def index
      @posts = Post.all
    end

    def open_posts
      @posts = Post.all
    end
  
    def show
    end
  
    def new
      @post = Post.new
    end

    def post_model_box
      @post = params["id"].present? ?Post.find(params["id"]) : Post.new
      @show_pos = params["id"].present? ? true : false
      @url = @post.image_url
      @title = params["title"]
      respond_to do |format|
        format.js { render 'post_model_box' }
      end
    end
  
    def create
      result = CreatePost.call(post_params: post_params, current_user: current_user)
      @post = result[:post]
      if !result.failure?
        respond_to do |format|
          format.js { render 'create_model_box' }
        end
      end
    end
  
    def edit
    end
  
    def update
      result = UpdatePost.call(post: @post, post_params: post_params, current_user: current_user)
      @post = result[:post]
      if !result.failure?
        respond_to do |format|
          format.js { render 'create_model_box' }
        end
      end
    end
  
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end
  
    private
  
    def set_post
      @post = Post.find_by(id: params[:id])
    end
  
    def post_params
      params.require(:post).permit(:title, :body, :status, :user_id, :position, :location, tag_ids: [], category_ids: [], attachments_attributes: [:id, :file, :_destroy])
    end
end
  

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/create_model_box.js.erb
$('#myModal').modal('hide');
document.getElementById('modalContainer').innerHTML = '<%= j render partial: "layouts/show_modal", locals: { modal_title: "Login", view_path: "posts/partials/create_post" } %>';
$('#myModal').modal('show');

var fileInput = document.getElementById('post_attachments_attributes_0_file');
var imagePreview = document.getElementById("img-preview");
fileInput.addEventListener("change", (e) => {
    console.log("hiii")
    if (e.target.files.length) {
        let src = URL.createObjectURL(e.target.files[0]);
        imagePreview.src = src;
    }
});

app/views/posts/index.html.erb
<div class="table-continer">
    <div class="table-actions">
        <div class="div_left_align"></div>
        <div class="div_right_align">
            <%= link_to 'Create Post', post_model_box_posts_path(title: "Create Post"), remote: true, id: 'showModalBtn', class: 'custom_button custom_success_btn sigin-out-block-btn' %>
        </div>
    </div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Body</th>
                <th>Published At</th>
                <th>status</th>
                <th>Added By</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Likes</th>
                <th>Comments</th>
                <th>Link</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <% @posts.each do |post| %>
                <%
                    image = post.attachments.last
                    url = nil
                    if image.present? && image.file.attached?
                        url = rails_blob_url(image.file, only_path: true)
                    end
                %>
                <tr>
                    <td data-label="ID"><%= post.id %></td>
                    <td data-label="Title"><%= post.title %></td>
                    <td data-label="Body"><%= post.body %></td>
                    <td data-label="PublishedDate"><%= format_date(post.published_at) %></td>
                    <td data-label="Status"><span class="active"><%= post.status %></span></td>
                    <td data-label="AddedBy"><img src="https://i.postimg.cc/FR5xjr4g/user.png" alt="" /><%= post.user.email%></td>
                    <td data-label="CreatedAt"><%= format_date(post.created_at) %></td>
                    <td data-label="UpdatedAt"><%= format_date(post.updated_at) %></td>
                    <td data-label="Likes">0</td>
                    <td data-label="Comments">0</td>
                    <td data-label="Link"><img id = "uploaded_image" src="<%= url %>"/></td>
                    <td data-label="Link">
                        <%= link_to post_model_box_posts_path(id: post, title: "Update Post"), remote: true, id: 'showModalBtn', class: "mr-2" do %>
                            <i class="fa-solid fa-pen-to-square text-primary"></i>
                        <% end %>

                        <%= link_to post_path(post),  method: :delete, data: { confirm: 'Are you sure?' } do %>
                            <i class="fa-solid fa-trash text-danger"></i>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/posts/open_posts.html.erb
<%
  grid_pattren = {
    grid1: {col: "1/2", row_diff: 2, row_inc: 0},
    grid2: {col: "2/3", row_diff: 1, row_inc: 0},
    grid3: {col: "2/3", row_diff: 1, row_inc: 1},
    grid4: {col: "1/2", row_diff: 1, row_inc: 1},
    grid5: {col: "1/2", row_diff: 1, row_inc: 1},
    grid6: {col: "2/3", row_diff: 2, row_inc:-1},
  }
  height = 1
  max_height = 6
  row_count = 1
%>

<div class="home-main-container">
    <div class="home-main-section-1">
       <section class="creative-carousal--hero">
		<div class="carousel-slider swiper-container-horizontal">
			<div class="swiper-wrapper">
                <% @posts.each do |post| %>
                    <% url = post.image_url %>
                	<div class="swiper-slide" data-background="<%= url %>" style="background-image: url(<%= url %>);">
					    <div class="inner"><h2><%= post.title&.capitalize %></h2> 
						    <a href="#">DISCOVER CASE</a> 
					    </div>
				    </div>
                <% end %>
			</div>
			<!-- End Of Swiper -->
			<div class="slide-progress"> 
				<span>01</span>
				<div class="swiper-pagination swiper-pagination-progressbar"><span class="swiper-pagination-progressbar-fill"></span></div>
				<span><%= @posts.count %></span> 
			</div>
			<!-- end of progress -->
			<div class="swiper-button-prev">PREV</div>
			<!-- end button-prev -->
			<div class="swiper-button-next">NEXT</div>
			<!-- end button-next -->
			</div>
		</section>
    </div>
    
    <div class="home-main-section-2">
        <div class="grid-layout">
              <% @posts.limit(6).each do |post| %>
        <% 
          value = grid_pattren["grid#{height}".to_sym]
          row_count += value[:row_inc]
        %>
        <div class="section-2-images" style="grid-column: <%= value[:col] %>; grid-row: <%= "#{row_count}/#{( value[:row_diff] + row_count)}" %>;">
            <div class="grid-content-container">
                  <div>
                   <p class="title-text"><%= post.title %></p>
                   <p class = "side-title-text">July 24</p>
                  </div>
                  <div class="d-flex">
                     <i class="fa-solid fa-location-dot pr-2"></i><p class="side-title-text"><%= "Banglore" %></p>
                  </div>
            </div>
            <div class="grid-image-container">
               <img src="<%= post.image_url %>" />
               <p class="home-img-cat">category</p>
               <a class="image_read_more">Read More</a>
            </div>
            <div class="post-action-container">
                <div class="like-comment-container">
                    <i class="fa-regular fa-heart text-normal"></i>
                    <i class="fa-regular fa-comment text-normal"></i>
                </div>
                <div class="share-container">
                    <i class="fa-solid fa-share text-normal"></i>
                </div>
            </div>
        </div>
        <% 
           height += 1
           if height > max_height
            height = 1
            row_count += 2
           end 
        %>
        <% end %>
        </div>
   </div>
</div>

<%= javascript_include_tag 'posts' %>

<style>
.post-action-container{
    display:flex;
    justify-content: space-between;
}

.post-action-container, .share-container{
    margin: 0px 10px 0px 10px;
}
.section-2-images{
    padding-bottom: 35px;
}

.grid-content-container{
    display: flex;
    width: 100%;
    padding: 0px 10px 0px 10px;
    justify-content: space-between;
}

.title-text{
    font-size: 17px;
    font-weight: 600;
    cursor: pointer;
    -webkit-transition: background-color 2s ease-out;
    margin: 0;
}

.side-title-text{
    font-size: 13px;
    font-weight: 200;
    cursor: pointer;
    -webkit-transition: background-color 2s ease-out;
    margin: 0;
}

.text-normal{
    font-size: 20px;
}
</style>

app/views/posts/post_model_box.js.erb
$('#myModal').modal('hide');
document.getElementById('modalContainer').innerHTML = '<%= j render partial: "layouts/show_modal", locals: { modal_title: @title, view_path: "posts/partials/post_action" } %>';
$('#myModal').modal('show');

var fileInput = document.getElementById('post_attachments_attributes_0_file');
var imagePreview = document.getElementById("img-preview");
fileInput.addEventListener("change", (e) => {
    console.log("hiii")
    if (e.target.files.length) {
        let src = URL.createObjectURL(e.target.files[0]);
        imagePreview.src = src;
    }
});

imagePreview.addEventListener('click', () => {
  fileInput.click();
});