config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'posts#open_posts'

  get 'about', to: 'home#about'

  resources :posts do
    collection do
      get 'post_model_box'
      get 'open_posts'
    end
  end

  namespace :users do
    get 'login_model_box', to: 'users#login_model_box', as: :login_model_box
    get 'sign_up_model_box', to: 'users#sign_up_model_box', as: :sign_up_model_box
    get 'forgot_password_modal_box', to: 'users#forgot_password_modal_box', as: :forgot_password_modal_box
    get 'get_more_options', to: 'users#get_more_options', as: :get_more_options
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/partials/_footer.html.erb
 <footer>
        <div class="footer-links">
            <%= nav_link_to 'Home', root_path %>
            <%= nav_link_to 'About', about_path %>
        </div>
        <div class="footer-social">
            <a href="#"><ion-icon name="logo-facebook" class="icon" alt="Facebook"></ion-icon></a>
            <a href="#"><ion-icon name="logo-twitter" class="icon" alt="Twitter"></ion-icon></a>
            <a href="#"><ion-icon name="logo-linkedin" class="icon" alt="LinkedIn"></ion-icon></a>
        </div>
        <div class="footer-contact">
            <p>Email: sminagendra@gmail.com</p>
            <p>Phone: +91 9019683872</p>
        </div>
        <div class="blog-signup">
            <input type="email" placeholder="Subscribe to our Blogs">
            <button class="custom_button custom_info_btn sigin-out-block-btn">Subscribe</button>
        </div>
</footer>

app/views/layouts/partials/_header.html.erb
<nav class='kae-nav-bar'>
    <div class="logo">
        <img src="<%= asset_path( 'logo.png' ) %>" alt="Logo Image">
    </div>
    <div class="hamburger">
        <div class="line1"></div>
        <div class="line2"></div>
        <div class="line3"></div>
    </div>
    <ul class="nav-links">
        <div class="navlink-list header-ul-lists">
          <li><%= nav_link_to 'Home', root_path %></li>
          <li><%= nav_link_to 'About', about_path %></li>
        </div>
        <div class="btn-list header-ul-lists">
          <% if user_signed_in? %>
            <li><%= link_to 'More', users_get_more_options_path, remote: true, id: 'showModalBtn', class: 'custom_button custom_success_btn sigin-out-block-btn' %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'custom_button custom_danger_btn sigin-out-block-btn' %></li>
          <% else %>
            <li><%= link_to 'Log in', users_login_model_box_path, remote: true, id: 'showModalBtn', class: 'custom_button custom_success_btn sigin-out-block-btn' %></li>
            <li><%= link_to 'Sign up', users_sign_up_model_box_path, remote: true, id: 'showModalBtn', class: 'custom_button custom_info_btn sigin-out-block-btn' %></li>
          <% end %>
        </div>
    </ul>
</nav>

<script>
const hamburger_menu = document.querySelector(".hamburger");
const navLinks = document.querySelector(".nav-links");
const links = document.querySelectorAll(".nav-links .header-ul-lists li");

hamburger_menu.addEventListener('click', ()=>{
   //Animate Links
    navLinks.classList.toggle("open");
    links.forEach(link => {
        link.classList.toggle("fade");
    });

    //Hamburger Animation
    hamburger_menu.classList.toggle("toggle");
});
</script>